// <auto-generated />
using System;
using GT.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GT.Storage.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190518183926_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GT.Models.Deed", b =>
                {
                    b.Property<Guid>("DeedId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CurrentCountUsers");

                    b.Property<string>("DescriptionPrivate");

                    b.Property<string>("DescriptionPublic")
                        .IsRequired();

                    b.Property<int>("MaxCountUsers");

                    b.Property<int>("MinCountUsers");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("State");

                    b.Property<Guid>("UserId");

                    b.HasKey("DeedId");

                    b.HasIndex("UserId");

                    b.ToTable("Deeds");
                });

            modelBuilder.Entity("GT.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GT.Models.UserDeed", b =>
                {
                    b.Property<Guid>("UserDeedId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DeedId");

                    b.Property<Guid>("UserId");

                    b.HasKey("UserDeedId");

                    b.ToTable("UserDeeds");
                });

            modelBuilder.Entity("GT.Models.Deed", b =>
                {
                    b.HasOne("GT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
